FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-stage
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Prod stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build-stage /app/out .
ENTRYPOINT ["dotnet", "LittleBooksBackend.dll"]